tdp/cli/__main__.py
tdp/cli/commands/dag.py
tdp/core/dag_dot.py

The new option `--cluster` for `dag` command group nodes inside cluster subgraph for each service.
`tdp dag hdfs_init -c -ct ranger_init`

Add "--cluster" for "dag" command to display node inside service

---

tdp/core/runner/ansible_executor.py

By default, python prints a newline at the end of the `print` function. Remove the endline because ansible already puts endlines itself.
This PR improves stdout readability.

runner: remove the trailing endline from stdout printing

---

README.md

`docs-generate` is used to regenerate automatic rst files
To generate actual documentation, it's `docs-html`

docs: fix documentation generation command

---

tdp/core/dag.py

makes the result from `glob` into a list, to keep the same behavior as before plus a generator object cannot be sent between processes

core: remove missing import, make yaml_files a list in factory

---

tdp/cli/commands/deploy.py

fix #144 
output:
```
"hive" repository is not in a clean state. Check that all modifications are committed.
"hadoop" repository is not in a clean state. Check that all modifications are committed.
Error: Some services are in a dirty state, commit your modifications.
```

cli: add hints on how to resolve cleanliness check on tdp deploy

---

tdp/cli/commands/dag.py

fix #158 
In this PR:
- `show` and the optional libraries from extras are imported later (at the start of the function), to prevent failing in the module loading phase.
- Improved output
```
2022-05-10 10:02:01,686 - DEBUG - tdp.<module> - Logger initialized
Error: You need to install the 'visualization' extras to be able to use the dag command. Run 'poetry install --extras visualization'
```

cli: import libraries from extras that are needed later

---

tdp/core/operation.py

Add a nullable attribute `component`  that will return the name of the component in an operation.
`component` should be None when `is_service` is true. Because a service by definition does not have a component.

feat(operation): add component attribute

---

poetry.lock
pyproject.toml
tdp/cli/__main__.py

fix #174 
This PR adds the possibility to configure environment variables with a .dotenv file.
This will either load the env file located at `$TDP_ENVIRONMENT_FILE` or, if the variable is not set, the `.env` file in the current working directory.
Not having a `.env` file does not fail the cli.
Example of a .env file:
```ini
TDP_COLLECTION_PATH=/opt/tdp-getting-started/ansible_roles/collections/ansible_collections/tosit/tdp
TDP_RUN_DIRECTORY=/opt/tdp-getting-started
TDP_VARS=/opt/tdp-getting-started/inventory/tdp_vars
TDP_SQLITE_PATH=/opt/tdp-getting-started/db_data/sqlite.db
```

feat: add dotenv to load environment variables from .env files

---

tdp/core/service_manager.py

This method is used to compute a component name (used for var file names) in the form `{service}_{component}`

feat: add method to compute the component name

---

tdp/core/repository/repository.py

When trying to only read vars, the file is created and added to staging.
This PR adds a boolean to fail instead when the file is missing.

feat: make open_var_file faillible

---

tdp/cli/commands/service_versions.py

fix #179 
The warning was caused because `latest_deployment_by_service` was built into a subquery tied to the session and then used inside the `in_` operator.
The recommended way is to construct a select query, independent from the session, and pass it to the `in_` operation.

fix: correct sqlalchemy warning in agg query

---

tdp/cli/commands/service_versions.py

Fixes #182
Modify ```sqlalchemy``` code to take into account the following SQL query:
```
SELECT max(service_log.deployment_id) AS deployment_id,service_log.service AS service,substr(service_log.version,1,7) AS version
FROM service_log JOIN operation_log
ON (service_log.deployment_id = operation_log.deployment_id AND operation_log.operation LIKE service_log.service || '\_%' ESCAPE '\')
WHERE operation_log.state = 'Success'
GROUP BY service_log.service,service_log.version
ORDER BY deployment_id,service;
```

cli: sql query improvement for tdp service-versions

---

docs/developer/cli/developer_quick_start.rst
tdp/cli/commands/browse.py
tdp/cli/commands/deploy.py
tdp/cli/commands/init.py
tdp/cli/commands/run.py
tdp/cli/commands/service_versions.py
tdp/cli/session.py

fix #184
/!\ Breaking change, `sqlite-path` replaced by `database-dsn`
This PR introduces the argument `database-dsn` as a replacement to `sqlite-path`.
The argument does not take a path anymore, but an sqlalchemy compatible datasource name (dsn).
Example for sqlite:
```bash
export TDP_DATABASE_DSN="sqlite:////data/tdp.db"
```
Example for postgresql:
```bash
export TDP_DATABASE_DSN="postgresql://tdp_user:tdp_password@localhost/tdp_dev_db"
```
If you use a sqlite backend, there's no python driver to install, since it's present in the standard library (you might need to install sqlite3 on your system though).
If you use another backend, such as Postgresql, you need to install the relevant python driver such a `psycopg2` or `psycopg2-binary` for instance.

feat: replace sqlite-path argument with database-dsn

---

tdp/cli/commands/service_versions.py

Fixes #188 
This will remove hard coded strings defined in the SQL query labels used by the client command line ```tdp service-versions```. Thoses are not used are completely removed.
For which is used, it is replaced by variable. And strings in result header are also replaced by variables.

cli: fix service-versions sql query labels

---

tdp/cli/commands/dag.py
tdp/cli/commands/default_diff.py
tdp/cli/commands/deploy.py
tdp/cli/commands/init.py
tdp/cli/commands/nodes.py
tdp/cli/commands/playbooks.py
tdp/cli/commands/run.py
tdp/cli/utils.py
tdp/core/collections.py
tdp/core/dag.py
tdp/core/runner/operation_runner.py
tdp/core/runner/test_operation_runner.py

Fix #190 
Add `Collections` class to handle collections order.
`Collections` class is used to load `Operation` from multiple `Collection` object. `Collections` allow to have `Collection` which override `Operation` from a previous loaded `Collection`. The loading order is important.
Moreover `Collections` handle `Operation` inside the DAG and `Operation` not in the DAG.

Run Operation not in DAG

---

tdp/cli/commands/browse.py

Fix #196 
The column about ```operations``` in ```deployments``` returned by ```tdp browse``` could be removed, because it can not contain a full list of operations, and this could be display with ```tdp browse <deployment_id>```.
By this way, we could thus reduce number of queries launched by ```tdp browse```.

cli: remove operations in tdp browse deployments

---

tdp/cli/commands/deploy.py
tdp/cli/commands/restart_required.py
tdp/cli/commands/run.py
tdp/core/runner/executor.py
tdp/core/runner/operation_runner.py

fix #204
In this PR:
- run_nodes now returns an iterator, giving back control to the deployment to the caller. It is still the caller responsibility to insert into database. An user can iterate through all the operations, and only insert the final deployment log. Or, he can insert along the way.

feat: update operations during deployment

---

tdp/cli/commands/browse.py
tdp/core/models/deployment_log.py
tdp/core/models/operation_log.py
tdp/core/models/service_log.py
tdp/core/runner/operation_runner.py

fix #207 
This PR replaces attribute names in the SQL schemas not to use reserved standard sql keywords.
The following attributes have been renamed:
- end -> end_time
- filter -> filter_expression
- start -> start_time
The following attributes were not renamed because they are not reserved keyword in the SQL standard:
- operation
- state
Source for reserverd keywords: https://en.wikipedia.org/wiki/SQL_reserved_words

feat: modify sql schema attribute not to use reserved keywords

---

docs/developer/core/variables.rst
tdp/cli/commands/default_diff.py
tdp/core/service_manager.py
tdp/core/test_variables.py
tdp/core/variables.py

fix #223
Simplification of variables handling.
Returning deepcopy on get was a bad idea, and made handling vars very unpythonic.
`_flush_on_write` was utopic because it wasn't called on inner dict, or if the key's value was another kind of container (append on a list).
It's easier and more sound to flush when closing. Relying on caller either using the `Variables.open()` values into a context manager, or calling `close()` himself.

feat: refactor variables

---

tdp/cli/commands/deploy.py
tdp/core/runner/operation_runner.py

fix: raise an error when parameters lead to an empty list of operations

---

tdp/core/models/service_component_log.py

Fixes #273
Having part of a composite primary key nullable is forbidden in Postgresql, therefore we needed to introduce a surrogate key to become the new primary key.

fix(model): introduce surrogate key in ServiceComponentLog

---

tdp/cli/commands/init.py
tdp/core/variables/cluster_variables.py

Fixes #301 
Here is a proposal for the linked issue to provide multiple paths. Those changes rely on Click's `multiple=True` option for command line options.
There are two ways to provide multiple paths :
- multiple `--overrides` from CLI :
```bash
tdp init --overrides my_vars/platform1 --overrides my_vars/dev
```
- multiple overrides paths from `TDP_OVERRIDES` environment variable :
```bash
export TDP_OVERRIDES=my_vars/platform1:my_vars/dev
tdp init
```
Both give the same output
```
2023-03-06 17:34:43,936 - INFO - tdp.cluster_variables.initialize_cluster_variables - hadoop is already initialized at 5f0a6bbb62d169c95d8c8079a989fd4200bcd04c
2023-03-06 17:34:43,942 - INFO - tdp.service_variables.update_from_variables_folder - Updating hadoop with variables from …
```

feat(cli/init): allow multiple overrides paths

---

tdp/core/deployment/deployment_iterator.py

Fixes #337 
I also added some comments and refactored some of the variables to improve code comprehension.

feat: held status after fail

---

tdp/core/deployment/test_deployment_plan.py
tdp/core/deployment/test_deployment_runner.py

Fix broken tests

---

docs/source/tdp.core.models.rst
tdp/cli/commands/browse.py
tdp/cli/commands/deploy.py
tdp/cli/commands/plan/reconfigure.py
tdp/cli/commands/service_versions.py
tdp/cli/queries.py
tdp/core/deployment/conftest.py
tdp/core/deployment/deployment_iterator.py
tdp/core/deployment/deployment_plan.py
tdp/core/deployment/test_deployment_plan.py
tdp/core/deployment/test_deployment_runner.py
tdp/core/models/__init__.py
tdp/core/models/component_version_log.py
tdp/core/models/deployment_log.py
tdp/core/models/test_db.py

Part of #348 
Rename the `service_component_log` table to `component_version_log` and rename related variables accordingly.

refactor: rename ServiceComponentLog to ComponentVersionLog

---

tdp/core/models/deployment_log.py

Fixes #365  
I replaced the order from OperaionLOg.start_time to OperationLog.operation_order

fix: modify order of OperationLog

---

tdp/conftest.py
tdp/core/collection.py
tdp/core/collections.py
tdp/core/dag.py
tdp/core/deployment/deployment_runner.py
tdp/core/test_collection.py

Remove unused methods from collection class.
Rename operations to playbooks to avoid confusion.
Fixes None
Refactor the `Collection` class:
- Remove unused properties (most of the paths are only used internally). Create a `_get_directory` method to handle the retrieval of dir without these properties.
- Rename "operations" to "playbooks" to better describe the objects in this context.
- Remove the `from_path` static method as it don't bring much (it takes the same parameters as `__init__`). The tests have been moved into their own method (it should make unit testing easier).

refactor: collection methods

---

tdp/cli/commands/plan/run.py
tdp/conftest.py
tdp/core/collections.py
tdp/core/dag.py
tdp/core/deployment/deployment_plan.py
tdp/core/deployment/test_deployment_plan.py
tdp/core/deployment/test_deployment_runner.py

Fixes #374
Fixes #357
I moved the logic checking if operations exist from cli `run` command to core `DeploymentPlan.from_operations`. 2 tests are still failing because they are using the DeploymentPlan.from_operations to test the DeploymentRunner with noop operations (which is not possible anymore). This raises some questions:
- Should we allow the `tdp plan run` command to take noop operations as arguments? If yes, this could lead to "empty" deployment, nothing will be executed.
- Should we keep those tests?

374 check if operation exist at deployment plan creation

---

tdp/core/models/deployment_log.py

Fixes None
Remove the following error.
> /tdp/core/deployment/deployment_iterator.py:92: RemovedIn20Warning: "ComponentVersionLog" object is being merged into a Session along the backref cascade path for relationship "DeploymentLog.component_version"; in SQLAlchemy 2.0, this reverse cascade will not take place.  Set cascade_backrefs to False in either the relationship() or backref() function for the 2.0 behavior; or to set globally for the whole Session, set the future=True flag (Background on this error at: https://sqlalche.me/e/14/s9r1) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
component_version_log.deployment = self.deployment_log

fix: remove sqlalchemy warning

---

tdp/cli/commands/deploy.py
tdp/cli/commands/plan/reconfigure.py
tdp/cli/commands/plan/test_reconfigure.py
tdp/cli/commands/stale/__init__.py
tdp/cli/queries.py
tdp/core/deployment/deployment_iterator.py
tdp/core/deployment/deployment_runner.py
tdp/core/deployment/test_deployment_runner.py
tdp/core/models/deployment_log.py
tdp/core/models/stale_component.py
tdp/core/models/test_deployment_log.py
tdp/core/models/test_stale_component.py
tdp/core/variables/cluster_variables.py

Part of #378 
- Reconfigure now uses stale component.
- Each deployment updates the stale table.

feat: reconfigure uses stale components

---

tdp/core/deployment/deployment_iterator.py

Fixes None
Fix iterator so that it can create version log for component **on each host**.

fix: iterator dissociate hosts for component version logs

---

tdp/core/variables/variables.py

Fixes #399
I found similar issue and fix here https://stackoverflow.com/questions/69817464/pyyaml-error-could-not-determine-a-constructor-for-the-tag-vault
Basically I used the ansible utils yaml parser instead of the default pyyaml parser. It seems like an OK fix to me but I might forget something.
I did test using a debug msg in a collection and the var is correctly decrypted.
The PR is provided as a suggestion, I'm not familiar enough with the lib anyway

fix: use ansible utils for parsing yaml

---

tdp/cli/commands/browse.py

Fixes #421
Example message:
```
➜ tdp browse  
2023-09-01 12:02:49,805 - DEBUG - tdp.<module> - Logger initialized
No deployments found, create a deployment plan with `tdp plan`.
```

feat: improve browse message

---

tdp/core/variables/service_variables.py

Part of #369
This seams to be already fixed:
> - Explicit the correct types for classes that inherit from the `Mapping` abc (as `Collections`)
> - Use `list` instead of `List`
I am not sure if there is smth else to refactor. Checked with [whats new in python 3.9](https://docs.python.org/3/whatsnew/3.9.html).

refactor: replace OrderedDict with dict

---

tdp/core/models/base.py
tdp/core/models/test_base.py

Fixes None
Create a to_dict method to get sqlalchemy model as dict. It is now used by str and will later be used in the browse method. I'll wait for this PR to be merged before implementing it.

refactor: add to_dict method to models

---

tdp/core/models/base.py

Having None values in the hosts column was confusing.
Fixes None
Replace `None` values by empty strings from the table of the `tdp browse` command. It was confusing to have `None` displayed in the "host" column.

Remove `None` values from `tdp browse` command output

---

tdp/cli/__main__.py

Fixes #423
This fixes the issue by using the default click behaviour being 
> By default, a group or multi command is not invoked unless a subcommand is passed. In fact, not providing a command automatically passes --help by default
If we do not want such behaviour, we should implement a context such as this:
```
@click.pass_context
def cli(ctx):
if ctx.invoked_subcommand is None:
click.echo('I was invoked without subcommand')
else:
click.echo('I am about to invoke %s' % ctx.invoked_subcommand)
```
It is a quick fix for a very minor behaviour. I haven't seen in the history why this behaviour was added (in PR #287)
Link: https://click.palletsprojects.com/en/7.x/commands/

423 `tdp` command with no arguments should print the usage help

---

tdp/cli/commands/plan/__init__.py
tdp/cli/commands/plan/ops.py
tdp/cli/commands/plan/test_ops.py

Fixes None
Rename `tdp plan run` to `tdp plan ops` to avoid confusions.

refactor: rename tdp plan run to tdp plan ops

---

tdp/cli/queries.py
tdp/core/models/sch_status_log.py

timestamp is a reserved SQL word.
Fixes None
Rename the `timestamp` column to `event_time` as `TIMESTAMP` is a reserved SQL keyword.

Rename `timestamp` column to `event_time`

---

tdp/cli/__main__.py
tdp/cli/commands/operations.py
tdp/cli/commands/test_operations.py

Fixes #476
- Changed the name of the command `tdp operation` to `tdp ops`.
- Fixed the issue where the `--host` argument was only working when adding the `--dag` option.

476 tdp operations

---

tdp/core/deployment/executor.py

Fixes None
- use += operator to compose the command
- resolve `ansible-playbook` command before executing the script

Resolve `ansible-playbook` command before execution

---

tdp/core/deployment/deployment_runner.py

Fixes #490 
If a host is provided for an operation, check if the operation is available for this host before executing it.
Log a custom error message in the database.
This is required to avoid edge case with the `--limit <host>` option on the `ansible-playbook` command.

Check operation availability on host before execution

---

tdp/cli/__main__.py
tdp/cli/utils.py

feat: catch exceptions

---

tdp/core/models/deployment_log.py
tdp/core/models/operation_log.py
tdp/core/models/sch_status_log.py

Fixes None
Remove `_log` suffix from `deployment_log` and `operation_log` table names  as they are not true logs.
I'll do a follow up PR to rename the classes accordingly.

refactor: rename deployment and operation tables

---

tdp/cli/commands/browse.py
tdp/cli/utils.py

Fixes None
When browsing through a deployment, it is not useful to display the first few words of each operation logs.
They are still visible when browsing the operation (`tdp browse <id> <operation>`

Prevent display full logs when browsing a deployment

---

tdp/cli/commands/deploy.py

Fixes None
Update operation records in the database after each operation execution. This has been broken by the last refactor.

fix: save state in the database after each operation execution

---

tdp/cli/commands/browse.py

Fixes None
Add an option to print last deployment in browse command as it is the most common usage.
Usage:
```sh
tdp browse --last
```

feat: `--last` option on `tdp browse`

---

tdp/cli/__main__.py
tdp/cli/commands/browse.py
tdp/cli/commands/dag.py
tdp/cli/commands/default_diff.py
tdp/cli/commands/deploy.py
tdp/cli/commands/init.py
tdp/cli/commands/ops.py
tdp/cli/commands/plan/dag.py
tdp/cli/commands/plan/resume.py
tdp/cli/commands/playbooks.py
tdp/cli/commands/status/edit.py
tdp/cli/commands/validate.py
tdp/cli/commands/vars/edit.py
tdp/cli/queries.py
tdp/cli/utils.py
tdp/core/collection.py
tdp/core/dag.py
tdp/core/deployment/deployment_runner.py
tdp/core/inventory_reader.py
tdp/core/models/deployment_model.py
tdp/core/operation.py

Improve wordings and punctuation

---

tdp/core/models/deployment_model.py

Fixes None
The `tdp plan ops` command used with the `--rolling-interval` option caused the deployment to failed because of an host issue. Host should not be specified for the `wait_sleep` playbook.

Prevent failure when rolling interval on `tdp plan ops`

---

README.md

#443: Update README.md

---

tdp/cli/commands/plan/__init__.py
tdp/cli/commands/plan/edit.py
tdp/cli/commands/plan/import_file.py
tdp/cli/commands/plan/test_edit.py
tdp/cli/utils.py

feat: import deployment plan from a file ; rebase done

---

tdp/core/variables/variables.py

Fixes None
Fix `Variables.merge` param type from `dict` to `MutableMapping` to be coherent with Ansible `merge_hash` method.

Fix `Variables.merge` param type

---

tdp/core/deployment/executor.py
tdp/test_utils.py
tdp/utils.py

Fixes None
Do not resolve the `ansible-playbook` command path if deployment is launched in dry mode (as the command wont be launched).
This is particularly useful when testing.

Do not resolve ansible in dry mode

---

tdp/core/variables/test_variables.py
tdp/core/variables/variables.py

Fixes None
IMO it makes more sense to check if the file is writable before flushing on disk.
Flushing on disk on a non writable file should raise an error.

Check if file is writable before flushing

---

tdp/core/variables/cluster_variables.py
tdp/core/variables/service_variables.py

Fixes None
No need to pass the name as an argument as it is induced by the variable directory path.

`ServiceVariables`: deduce service name from repository path

---

tdp/core/variables/cluster_variables.py
tdp/core/variables/service_variables.py
tdp/core/variables/variables.py

Fixes None
Simplifies the import of variables which was split accros multiple methods that were not reused. Current version feels a bit over-engineered, probably because at first we wanted to expose some public API with `tdp-lib`.

`ServiceVariables`: merge variables importation logic

---

tdp/core/collection.py
tdp/core/collections.py
tdp/core/deployment/deployment_runner.py
tdp/core/deployment/executor.py
tdp/core/entities/operation.py
tdp/core/entities/test_operation.py
tdp/core/test_collection.py

Fixes None
Change the `Collection.playbooks` properties so that it maps operation names to `Playbook` object instead of playbook Paths.
In another PR, we should remove hosts from `Operation` definition so that host are only stored in `Playbook`.

Initialize `Playbook` entities inside of `Collection`

---

tdp/core/collections.py
tdp/core/models/deployment_model.py

Fixes None
Deleted the function `check_operations_exist` in `collections` since the a function called `check_operation_exists` already exists and can be looped to achieve the same.

refactor: deleted check_operations_exist function

---

tdp/core/variables/service_variables.py

Fixes None
Renamed the `get_variables` function in class `ServiceVariables` to `get_component_variables` which fits more its goal. The function is not currently used in TDP-lib, however it will very probably be used in the upcoming TDP-server in the endpoint `/api/v1/variables/{service_id}/components/{component_id}`.

suppressed get_variables function in ServiceVariables

---

tdp/core/variables/variables.py

Fixes None
- Provide more meaningful doc for the class
- Use parent initializer

Refactor _VariablesIOWrapper

---

tdp/cli/commands/plan/dag.py
tdp/cli/commands/plan/import_file.py
tdp/cli/commands/plan/ops.py
tdp/cli/commands/plan/reconfigure.py
tdp/cli/params/plan/__init__.py
tdp/cli/params/plan/force_option.py

Fixes #513 
- Added `y/N` confirmation to override existing deployment plan in plan dag, reconfigure, import and ops.
- Added `--force` option to automatically override existing deployment plan without asking the question.

513 prevent overriding existing plan

---

tdp/cli/commands/conftest.py
tdp/cli/commands/plan/test_dag.py
tdp/cli/commands/plan/test_ops.py
tdp/cli/commands/plan/test_reconfigure.py
tdp/cli/commands/plan/test_resume.py
tdp/cli/commands/status/test_edit.py
tdp/cli/commands/status/test_generate_stales.py
tdp/cli/commands/status/test_show.py
tdp/cli/commands/test_deploy.py
tdp/cli/commands/test_init.py
tdp/conftest.py

Fixes None
This PR is necessary for the PR Dev/alembic migration #563. When we integrate Alembic in the `init` command, it creates a new engine and synchronization problems occur between the engines when launching the unit tests although it works manually when we perform one command after another. Therefore, the `init` command has been left out of all unit tests and replaced with hard coded initialization except the test which specifically tests the `init` command of course.
The engine is created and closed also in the tests since we import the functions with the `click` decorators which take as input a `database-dsn` and not an engine.

refactor: engine in test procedure

---

tdp/dao.py

Fixes None
`return self.session.query(DeploymentModel).get(id)` is deprecated in sqlalchemy 2.0 and will not be supported in next version.

fix: deprecated way to query in sqlalchemy

---

tdp/cli/params/database_dsn_option.py

Fixes None
The function `database_dsn_option` returns an engine while we also need the database-dsn. This PR enables the the function to return both.

refactor: database_dsn_option parameter to return either engine or dsn

---

tests/conftest.py
tests/unit/test_dao.py

Fixes None
Test for dao get_deployment query.

feat: test dao get_deployment

---

tdp/cli/__main__.py

Fixes None
The `CatchGroup` class is currently intercepting all exceptions, removing their stack trace. However, it shouldn't intercept errors coming from the core lib. Each command should properly catch its potential errors and eventually manage it through `[ClickException](https://click.palletsprojects.com/en/7.x/api/#click.ClickException)`.

Remove `CatchGroup` class

---

tdp/cli/commands/default_diff.py
tdp/core/variables/__init__.py

Fixes None
For now `merge_hash` was imported / re-exported from `variables`  to be used by `default_diff`.
This PR import `merge_hash` from ansible  in `default_diff` directly.

Import `merge_hash` from ansible directly

---

tdp/core/dag.py

Fixes None
- Get rid of red error marker in get_components_from_service in Collections class.
- Get rid of red error marking in Dag class.

fix: get rid of red error marker in get_components_from_service

---

tdp/cli/commands/browse.py
tdp/dao.py
tests/unit/test_dao.py

Fixes #616
Changed the order in query. Now showing the deployments in descending order.

`browse` the last deployments

---

tdp/cli/commands/status/edit.py
tdp/cli/commands/status/show.py
tdp/core/entities/hosted_entity_status.py
tdp/core/models/sch_status_log_model.py
tdp/dao.py

Fixes None
While not being totally implemented, the `is_active` property already show some issues (how to define an "active" component). As discussed, we'll try to implement this check in another way.

Remove `is_active`

---

scripts/playbooks.py
tdp/cli/commands/ops.py
tdp/core/cluster_status.py
tdp/core/collections/collection_reader.py
tdp/core/collections/collections.py
tdp/core/dag.py
tdp/core/dag_dot.py
tdp/core/deployment/deployment_iterator.py
tdp/core/deployment/deployment_runner.py
tdp/core/entities/operation.py
tdp/core/inventory_reader.py
tdp/core/models/deployment_model.py
test_dag_order/conftest.py
tests/unit/core/test_collection_reader.py
tests/unit/core/test_collections.py
tests/unit/core/test_filters.py

Fixes None
Transform the `Operation` class to an abstract class that is declined in several implementations:
- `PlaybookOperation(Operation)`
- `OperationNoop(Operation, ABC)`
- `DagOperation(Operation, ABC)`
- `DagOperationNoop(DagOperation, OperationNoop)`
- `DagOperationWithPlaybook(DagOperation, PlaybookOperation)`
- `ForgedDagOperation(DagOperation, ABC)`
- `ForgedDagOperationNoop(DagOperationNoop, ForgedDagOperation)`
- `ForgedDagOperationWithPlaybook(DagOperationWithPlaybook, ForgedDagOperation)`
- `OtherPlaybookOperation(PlaybookOperation)`
The instanciation of the above classes is now ONLY done by the `Collections` class initialization, nowhere else.
The `Collections` class now only exposes a single dict with all available operations, all other previous operations properties are …

Introduce new operation entities

---

tdp/core/collections/collections.py
tdp/core/entities/operation.py

Fixes None
Remove the `OperationName.clone` method. A clone method shouldn't take any argument, this was a misconception.

refactor: remove OperationName.clone method

---

tdp/cli/commands/init.py
tdp/cli/params/vars_option.py
tdp/core/variables/cluster_variables.py

This pull request introduces several changes to improve the handling and validation of the TDP variables directory across multiple files. Key updates include stricter validation of paths, enhanced error handling, and improved initialization logic.
* [`tdp/cli/params/vars_option.py`](diffhunk://#diff-494099f597cd7735a39c885d27fd81aa50b4e389b377f070386599d75cedce5aL23-R30): Updated the `--vars` parameter type to enforce stricter validation, ensuring the path is a writable directory and disallowing file paths.
* [`tdp/cli/commands/init.py`](diffhunk://#diff-7cacdf5bad9e356bbc332e9181df042d31152d4769c705c7acbebb7c7dddf22bR43-R46): Modified the `init` function to create the TDP variables directory if it does not exist, ensuring smoother initialization and providing user feedback.
* …

`init` creates vars directory if it does not exists

---

tdp/cli/__main__.py
tdp/cli/logger.py

This pull request introduces enhancements to the logging system in the `tdp` CLI to improve configurability and early logging setup. Key changes include adding support for early logging initialization, refining log level handling, and simplifying the CLI entry point. 
* Introduced a new function, `setup_early_logging`, to configure logging before CLI parsing, ensuring logs are available for early operations. (`tdp/cli/logger.py`, [tdp/cli/logger.pyR5-R90](diffhunk://#diff-c980d63fdd53225fe9f6fb036b8871c5e8e0fed8b8eeedd5c9042bda0bf94eafR5-R90))
* Added a `get_early_logger` function to retrieve a pre-configured logger for use before full CLI initialization. (`tdp/cli/logger.py`, [tdp/cli/logger.pyR5-R90](diffhunk://#diff-c980d63fdd53225fe9f6fb036b8871c5e8e0fed8b8eeedd5c9042bda0bf94eafR5-R90) …

CLI logging setup with early logger and dynamic log level

---

pyproject.toml
tdp/cli/__main__.py

This pull request refactors the CLI entry point in the `tdp` project to streamline command execution. The changes involve replacing the `main` function with direct invocation of the `cli` function and updating the `pyproject.toml` configuration accordingly.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L47-R47): Updated the CLI entry point from `tdp.cli.__main__:main` to `tdp.cli.__main__:cli` to align with the refactored structure.
* [`tdp/cli/__main__.py`](diffhunk://#diff-0162a57e33759c76f406e0be7a39701bb99c9dc54b2e22cbcc4d95754eab45efL72): Removed the `main` function and replaced its usage with direct invocation of the `cli` function, simplifying the command execution flow. …

Simplify CLI entry point by removing `main` function

---

tdp/core/dag.py

Fix the `topological_sort_key` method from the `Dag` class. The method should not use a subgraph as it removes not direct edges, which create invalid sorting.
Note: Computing a subgraph may be possible by applying [`transitive_closure`](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.dag.transitive_closure.html) to the graph before creating the subgraph.

fix: remove subgraph from topo sort
