TOSIT-IO/tdp-lib

- tdp/components/hdfs.yml
- tdp/components/yarn.yml
fix #134 
follow https://github.com/TOSIT-IO/tdp-collection/pull/231
> dag: add exporter_jmx for yarn

- tdp/components/hdfs.yml
> dag: add hdfs_jmx-exporter_config as hdfs_namenode_formatzk dependency

- tdp/core/dag.py
> Add custom topological order for services

- tdp/core/dag.py
> core: add "exporter" service priority before "zookeeper"

- tdp/components/zookeeper.yml
fix #153 
follow https://github.com/TOSIT-IO/tdp-collection/pull/248
> dag: add exporter_jmx for zookeeper

- docs/developer/cli/index.rst
- tdp/cli/__main__.py
- tdp/cli/commands/run.py
- tdp/cli/utils.py
- tdp/core/runner/ansible_executor.py
fix #161
Add run command to deploy a single node
In this PR:
- New `run` command which will execute a single playbook. Noop nodes will raise an error.
> cli: add run command

- tdp/core/dag.py
> feat(dag): add Spark3 service priority before Knox

- docs/developer/cli/developer_quick_start.rst
> fix(docs): add targets flag to deploy

- docs/developer/cli/index.rst
- docs/tdp.cli.commands.rst
- tdp/cli/__main__.py
- tdp/cli/commands/playbooks.py
Fix #63 
Playbooks generated are in https://github.com/TOSIT-IO/tdp-collection/pull/194
> Add playbooks command to generate meta playbooks

- tdp/cli/commands/browse.py
Use `fetch_one_or_none()` when the query should return an unique result.
Raise a click error when the result does not exist in database.
> fix: check queries with unique results

- poetry.lock
- pyproject.toml
> fix: pin typing-extensions library

- tdp/cli/commands/service_versions.py
fix #193 
Split the query in 2.
`latest_success_for_each_service` is the subquery getting the latest deployment id for each service.
`service_logs_matching_subquery` is the query returning the associated records.
SQL equivalent:
```sql
SELECT S1.DEPLOYMENT_ID, S1.SERVICE, S1.VERSION
FROM SERVICE_LOG S1
WHERE (S1.DEPLOYMENT_ID, S1.SERVICE) IN
(SELECT MAX(SERVICE_LOG.DEPLOYMENT_ID) AS MAX_DEPLOYMENT_ID,
SERVICE_LOG.SERVICE
FROM SERVICE_LOG
JOIN OPERATION_LOG ON SERVICE_LOG.DEPLOYMENT_ID = OPERATION_LOG.DEPLOYMENT_ID
AND OPERATION_LOG.OPERATION LIKE SERVICE_LOG.SERVICE || '\_%' ESCAPE '\\'
WHERE OPERATION_LOG.STATE = 'Success'
GROUP BY SERVICE_LOG.SERVICE)
ORDER BY S1.DEPLOYMENT_ID DESC;
```
(had to add an \ to ESCAPE '\\', true query does not require it, but github syntax coloration isn't …
> fix: correct service-versions to return only the latest successful deployment

- tdp/cli/__main__.py
- tdp/cli/commands/dag.py
- tdp/cli/commands/default_diff.py
- tdp/cli/commands/deploy.py
- tdp/cli/commands/init.py
- tdp/cli/commands/nodes.py
- tdp/cli/commands/playbooks.py
- tdp/cli/commands/queries.py
- tdp/cli/commands/restart_required.py
- tdp/cli/commands/run.py
- tdp/cli/commands/service_versions.py
- tdp/core/runner/operation_runner.py
- tdp/core/runner/test_operation_runner.py
Fix #24 
Add restart required feature
Add a new CLI command `restart-required` which configure and restart needed services/components if a service/component DAG ancestors configuration is modified.
> Restart required

- tdp/cli/commands/browse.py
Changes in this PR:
- Separate business logic from display
- Use `joinedload` to eagerly load relationships (reduces total number of requests)
> refactor(browse): separate business logic from display

- tdp/core/runner/operation_runner.py
> fix: invert foreign dependency

- tdp/cli/commands/deploy.py
- tdp/cli/commands/run.py
- tdp/core/models/deployment_log.py
- tdp/core/runner/operation_runner.py
> feat: make operation runner able to run list of operations

- tdp/core/models/test_db.py
- tdp/core/runner/test_operation_runner.py
> fix: fix unit tests

- tdp/cli/commands/restart_required.py
- tdp/core/models/deployment_log.py
- tdp/core/runner/operation_runner.py
> fix: render correct filter pattern

- tdp/cli/commands/deploy.py
- tdp/cli/commands/restart_required.py
- tdp/cli/commands/run.py
> feat(cli): do not write in the database in dry mode

- tdp/cli/commands/default_diff.py
- tdp/cli/commands/deploy.py
- tdp/cli/commands/init.py
- tdp/cli/commands/restart_required.py
- tdp/cli/commands/run.py
> fix: enable relative path in tdp_vars parameter

- tdp/cli/commands/run.py
- tdp/core/runner/operation_runner.py
> feat: make run able to deploy operation outside of the dag

- docs/developer/cli/index.rst
- tdp/cli/commands/init.py
- tdp/core/service_manager.py
Add option to add overrides to tdp initialization.
> feat: add possibility to add overrides to tdp init

- tdp/core/service_manager.py
- tdp/core/variables.py
> fix: add opening mode for variables

- tdp/cli/commands/restart_required.py
- tdp/core/runner/operation_runner.py
> fix: add noop check in operation plan from dag

- tdp/core/variables/service_variables.py
We need a method to be able to get variables from a service, without having to use repository / variables outside of ServiceVariables.
> feat: add method to get copy of any component variables

- tdp/cli/commands/dag.py
- tdp/cli/commands/nodes.py
- tdp/cli/commands/playbooks.py
- tdp/core/dag.py
- tdp/core/runner/operation_runner.py
> feat: refactor Dag method to return Operation instance instead of str

- .github/PULL_REQUEST_TEMPLATE.md
> chore: pull request template

- .gitignore
> chore: ignore .env files

- tdp/core/runner/operation_runner.py
Fixes #243
Naive implementation to support noop as success. A rework to Deployment is coming a later date.
> fix: consider noop as success

- tdp/cli/commands/run.py
- tdp/core/runner/operation_runner.py
> fix: make operations string for targets when operation plan provided with operations

- tdp/cli/commands/run.py
> feat(tdp-run): support variadic args

- .pre-commit-config.yaml
- tdp/core/topology.py
- tdp/core/variables/service_variables.py
- tdp/core/variables/test_variables.py
> Remove unused imports

- tdp/core/runner/deployment_iterator.py
- tdp/core/runner/test_deployment_runner.py
> fix: fix operation don't stop when failed

- tdp/cli/commands/init.py
> feat(cli): make overrides settable through env vars

- tdp/cli/__main__.py
- tdp/cli/commands/browse.py
- tdp/cli/commands/queries.py
- tdp/cli/commands/resume.py
- tdp/core/models/deployment_log.py
- tdp/core/models/deployment_type_enum.py
- tdp/core/runner/deployment_plan.py
- tdp/core/runner/test_deployment_plan.py
Fixes #225 
New implementation from #225 following a discussion with @gboutry:
- Here `tdp resume` is a new command
- `--id` is an optional parameter
- The logic was moved to the `from_resume` as commented in #256 by @rpignolet 
- `DeploymentTypeEnum` implemented
> feat: add resume command

- tdp/cli/commands/deploy.py
- tdp/cli/commands/restart_required.py
- tdp/cli/commands/resume.py
- tdp/cli/commands/run.py
> fix(cli): raise error on deployment failure

- tdp/cli/commands/playbooks.py
> fix(cli/playbooks): comment noop services

- tdp/cli/commands/browse.py
> fix: display enum name instead of complete name

- tdp/core/models/__init__.py
- tdp/core/runner/deployment_plan.py
- tdp/core/runner/test_deployment_plan.py
- tdp/core/runner/test_deployment_runner.py
> feat: support resuming any deployment type

- tdp/cli/commands/deploy.py
> feat: homogenize deploy api with from dag api

- tdp/core/dag.py
> fix: emit operation only on missing noop restarts

- tdp/cli/__main__.py
- tdp/cli/commands/deploy.py
- tdp/cli/commands/queries.py
- tdp/cli/commands/reconfigure.py
- tdp/cli/commands/resume.py
- tdp/cli/commands/run.py
- tdp/core/models/deployment_type_enum.py
- tdp/core/repository/git_repository.py
- tdp/core/runner/__init__.py
- tdp/core/runner/conftest.py
- tdp/core/runner/deployment_iterator.py
- tdp/core/runner/deployment_plan.py
- tdp/core/runner/test_deployment_plan.py
- tdp/core/runner/test_deployment_runner.py
- tdp/core/variables/service_variables.py
Fixes #271
After much consideration, I decided to rename `restart-required` into `reconfigure` as the goal to this command is to re-configure needed services, and restarting is an implementation detail.
Fixed a bug when config or start/restart would be a noop and therefore not registered in the database.
> Refactor Restart Required

- tdp/core/runner/__init__.py
> fix: export deployment plan exceptions

- .gitignore
> chore: ignore nlsp settings

- tdp/core/variables/service_variables.py
> fix: sort service vars paths for validation

- tdp/cli/commands/deploy.py
- tdp/cli/commands/init.py
- tdp/cli/commands/reconfigure.py
- tdp/cli/commands/resume.py
- tdp/cli/commands/run.py
- tdp/cli/utils.py
> feat: enable validation on deploying commands

- tdp/cli/commands/playbooks.py
`--for-collection` option generate meta playbooks only for specific collections (can be multiple)
Generate meta for `tdp-collection`:
```
tdp playbooks --for-collection tdp
```
Generate meta for `tdp-collection-extras`:
```
tdp playbooks --for-collection tdp_extra
```
Fixes #235
> feat(cli/playbooks): add --for-collection option

- tdp/conftest.py
- tdp/core/collection.py
- tdp/core/collections.py
- tdp/core/deployment/conftest.py
- tdp/core/test_collection.py
- tdp/core/test_collections.py
Fixes #305 
Before doing the feature, I wrote test for `Collection` and `Collections` class in order to test the merge feature.
> dag operations merge

- tdp/core/deployment/deployment_iterator.py
Fixes None
Import Iterator from abc (instead of typing).
> fix: import iterator from abc

- tdp/cli/commands/deploy.py
- tdp/cli/commands/reconfigure.py
- tdp/cli/commands/resume.py
- tdp/cli/commands/run.py
- tdp/cli/utils.py
> feat: add mock deploy

- tdp/core/variables/cluster_variables.py
> fix: prevent init fail when empty override

- tdp/cli/commands/playbooks.py
- tdp/core/dag.py
- tdp/core/dag_dot.py
- tdp/core/deployment/deployment_iterator.py
- tdp/core/models/deployment_log.py
- tdp/core/models/operation_log.py
- tdp/core/operation.py
- tdp/core/variables/service_variables.py
Fixes None
- Rename legacy names
- Remove unused logger
> feat: rename legacy name in collection

- tdp/cli/commands/dag.py
- tdp/cli/commands/deploy.py
- tdp/cli/session.py
- tdp/cli/utils.py
- tdp/core/collection.py
- tdp/core/collections.py
- tdp/core/dag.py
- tdp/core/dag_dot.py
- tdp/core/deployment/ansible_executor.py
- tdp/core/deployment/conftest.py
- tdp/core/deployment/deployment_iterator.py
- tdp/core/deployment/deployment_plan.py
- tdp/core/deployment/deployment_runner.py
- tdp/core/deployment/executor.py
- tdp/core/deployment/test_deployment_runner.py
- tdp/core/models/base.py
- tdp/core/models/deployment_log.py
- tdp/core/models/operation_log.py
- tdp/core/models/service_component_log.py
- tdp/core/models/state_enum.py
- tdp/core/operation.py
- tdp/core/repository/git_repository.py
- tdp/core/repository/repository.py
- tdp/core/repository/test_git_repository.py
- tdp/core/topology.py
- tdp/core/variables/cluster_variables.py
- tdp/core/variables/service_variables.py
- tdp/core/variables/test_variables.py
Fixes None
- Add types on methods args
- Add docstrings
> feat: add types and docstrings

- tdp/cli/commands/plan/run.py
Fixes None
Wrap the `deployment_plan` with `try`/`except` to raise the exception using click (as it is for the other mode of deployment).
> fix: raise exception with click

- pyproject.toml
Fixes issue #304 
As stated in : https://github.com/ultralytics/yolov5/issues/414
minimum version of pyYAML have to be > 3.13
Fixes #
> fix: add minimum version for pyYAML

- tdp/cli/commands/browse.py
- tdp/cli/queries.py
Fixes #343 
Add optional type to Deployment Log type in the get_planned_deployment_log return
> [feat] add plan option to browse command

- docs/source/conf.py
- tdp/cli/commands/playbooks.py
- tdp/core/deployment/deployment_plan.py
- tdp/core/deployment/deployment_runner.py
Fixes None
Remove unused property, import and add a comment.
> refactor: remove unused property

- tdp/cli/commands/browse.py
Fixes #349
It now looks like this:
> fix: improve browse output

- tdp/core/deployment/deployment_plan.py
> [doc] Minor fix docstrings

- tdp/core/models/deployment_log.py
Fixes #317 
The null value in the target and source columns of the deployment_log table is changed to JSON.NULL < null > after running the command: tdp plan dag
> fix: null value in deployment deployment log

- tdp/cli/queries.py
- tdp/core/dag.py
- tdp/core/variables/service_variables.py
Fixes None
- Fix wrong / missing types
- Add params descriptions
> fix: wrong types and missing param description

- tdp/cli/commands/browse.py
Fixes None
For the browse command:
- add types
- add docstrings
- rename internal functions to start with a `_`
> feat: add types and docstrings for browse command

- tdp/core/deployment/deployment_plan.py
Fixes #361 
ORM model may be improved to automatically query the operation logs ordered by `order`. This could be done in another issue.
> fix tdp resume command

- tdp/core/dag.py
Fixes None
Fix wrong type on dag
> fix: wrong type

- tdp/cli/commands/test_deploy.py
> Fix deploy cli test

- tdp/cli/commands/plan/reconfigure.py
- tdp/cli/queries.py
- tdp/core/collections.py
- tdp/core/deployment/conftest.py
- tdp/core/deployment/deployment_plan.py
- tdp/core/deployment/test_deployment_plan.py
- tdp/core/repository/git_repository.py
- tdp/core/repository/repository.py
- tdp/core/repository/test_git_repository.py
- tdp/core/service_component_name.py
- tdp/core/variables/cluster_variables.py
- tdp/core/variables/service_variables.py
Part of #348 
Refactor `ServiceVariables.component_modified`:
- Rewrite `ServiceVariables.component_modified` to :
```diff
- ServiceVariables.components_modified(self, dag: Dag, version: str) -> List[Operation]
+ ServiceVariables.modified_components(self, collections: Collections, version: str) -> Set[Tuple[str, str]]
```
- Create `ClusterVariables.modified_component` to reproduce the result of `ServiceVariables.component_modified` on the whole configuration.
- Create methods to check is a component has been modified:
- `ServiceVariables.is_service_component_modified_from_version(service_component: ServiceComponentName, version: str) -> bool`
- `Repository.is_file_modified(commit: str, file: Union[str, os.PathLike]) -> bool`
- Update the consumer functions accordingly (`tdp plan …
> Refactor modified components

- README.md
- poetry.lock
- pyproject.toml
- tdp/core/variables/service_variables.py
- tdp/core/variables/variables.py
> chore: update python to 3.9 and ansible-core to 2.15.1

- poetry.lock
- pyproject.toml
- tdp/cli/commands/deploy.py
- tdp/core/deployment/deployment_iterator.py
- tdp/core/models/component_version_log.py
- tdp/core/models/deployment_log.py
- tdp/core/models/operation_log.py
- tdp/core/models/stale_component.py
> 385 upgrade sqlalchemy

- tdp/core/deployment/test_deployment_runner.py
Fixes None
Fixes tests that broke after DeploymentIterator refactor.
> fix: rewrite tests after iterator refactor

- tdp/cli/commands/plan/run.py
- tdp/core/deployment/deployment_runner.py
- tdp/core/deployment/executor.py
- tdp/core/deployment/test_deployment_runner.py
- tdp/core/models/deployment_log.py
- tdp/core/models/operation_log.py
- tdp/core/models/test_deployment_log.py
> feat: add extra vars feature for operation/playbook

- tdp/cli/commands/conftest.py
- tdp/cli/commands/plan/test_dag.py
- tdp/cli/commands/plan/test_reconfigure.py
- tdp/cli/commands/plan/test_resume.py
- tdp/cli/commands/plan/test_run.py
- tdp/cli/commands/stale/test_stale.py
- tdp/cli/commands/test_default_diff.py
- tdp/cli/commands/test_deploy.py
- tdp/cli/commands/test_init.py
- tdp/cli/commands/test_nodes.py
- tdp/cli/commands/test_playbooks.py
- tdp/cli/commands/test_service_versions.py
- tdp/cli/commands/test_validate.py
- tdp/conftest.py
- tdp/core/conftest.py
- tdp/core/deployment/test_deployment_runner.py
- tdp/core/models/test_base.py
- tdp/core/models/test_db.py
- tdp/core/models/test_deployment_log.py
- tdp/core/repository/test_git_repository.py
- tdp/core/test_collection.py
- tdp/core/variables/test_variables.py
Fixes None
- Add types on tests parameters to help identify errors in test implementation.
- Display command output when cli test fails
> Add types on tests

- tdp/cli/commands/dag.py
Fixes None
Avoid importing package to test their availability using `importlib.util.find_spec`
> refactor: package availability check

- tdp/cli/commands/deploy.py
- tdp/cli/commands/service_versions.py
- tdp/core/conftest.py
- tdp/core/deployment/deployment_iterator.py
- tdp/core/models/component_version_log.py
- tdp/core/models/stale_component.py
- tdp/core/models/test_db.py
- tdp/core/models/test_stale_component.py
> 396 add host support for stale command

- tdp/core/dag.py
- tdp/core/models/deployment_log.py
Fixes None
Fix type errors for `DeploymentLog`
> fix: deployment log types

- tdp/core/repository/git_repository.py
- tdp/core/repository/repository.py
Fixes None
Fixes types on repository classes
> fix: repository types

- tdp/core/deployment/deployment_runner.py
- tdp/core/models/deployment_log.py
- tdp/core/models/state_enum.py
- tdp/core/test_baseenum.py
- tdp/core/utils.py
Fixes None
Create a `BaseEnum` class which meet our requirements.
> Refactor state enum

- tdp/cli/commands/browse.py
- tdp/cli/commands/default_diff.py
- tdp/cli/commands/deploy.py
- tdp/cli/commands/init.py
- tdp/cli/commands/plan/dag.py
- tdp/cli/commands/plan/reconfigure.py
- tdp/cli/commands/plan/resume.py
- tdp/cli/commands/plan/run.py
- tdp/cli/commands/plan/test_dag.py
- tdp/cli/commands/plan/test_reconfigure.py
- tdp/cli/commands/plan/test_resume.py
- tdp/cli/commands/plan/test_run.py
- tdp/cli/commands/service_versions.py
- tdp/cli/commands/stale/__init__.py
- tdp/cli/commands/test_deploy.py
- tdp/cli/commands/validate.py
- tdp/cli/queries.py
- tdp/cli/session.py
- tdp/cli/utils.py
Fixes None
Miscellaneous refactor across the cli. I suggest to review this PR commit by commit.
> Refactor clean cli code

- tdp/cli/commands/browse.py
> fix: typo in browse command

- tdp/cli/commands/stale/__init__.py
- tdp/core/collections.py
- tdp/core/dag.py
- tdp/core/models/deployment_log.py
- tdp/core/models/stale_component.py
- tdp/core/operation.py
- tdp/core/repository/git_repository.py
- tdp/core/service_component_host_name.py
- tdp/core/service_component_name.py
- tdp/core/variables/cluster_variables.py
- tdp/core/variables/service_variables.py
> refactor: update stale and from_stale to take host into account

- tdp/core/variables/variables.py
> 418 `tdp init` fails due to AnsibleJSONDecoder

- tdp/cli/commands/plan/reconfigure.py
- tdp/conftest.py
- tdp/core/collections.py
- tdp/core/models/deployment_log.py
- tdp/core/models/test_deployment_log.py
Add `--rolling-interval` option for `tdp plan reconfigure` command.
Fixes #288
> feat: add rolling restart feature

- tdp/cli/commands/deploy.py
- tdp/cli/queries.py
- tdp/core/deployment/deployment_iterator.py
- tdp/core/deployment/deployment_runner.py
- tdp/core/deployment/test_deployment_runner.py
- tdp/core/models/deployment_log.py
- tdp/core/models/test_deployment_log.py
- tdp/core/models/test_models.py
Fixes None
Store deployment plan options in a JSON object.
> refactor: save deployment options as json

- tdp/core/models/base.py
Fixes None
Define base model class in sqlalchemy 2.0 style
> Refactor Base model definition

- tdp/cli/commands/browse.py
- tdp/cli/commands/service_versions.py
- tdp/core/models/base.py
- tdp/core/models/component_version_log.py
- tdp/core/models/operation_log.py
- tdp/core/models/test_base.py
Fixes None
- Define custom formater along with model definition.
- Refactor `browse` and `service-versions`to use those new methods.
> Refactor browse command

- tdp/cli/commands/browse.py
- tdp/cli/session.py
- tdp/conftest.py
- tdp/core/collection.py
- tdp/core/collections.py
- tdp/core/conftest.py
- tdp/core/dag.py
- tdp/core/deployment/deployment_iterator.py
- tdp/core/deployment/executor.py
- tdp/core/models/deployment_log.py
- tdp/core/repository/git_repository.py
- tdp/core/repository/repository.py
- tdp/core/variables/cluster_variables.py
- tdp/core/variables/service_variables.py
- tdp/core/variables/test_variables.py
> Remove deprecated types

- tdp/cli/commands/plan/reconfigure.py
- tdp/cli/commands/plan/run.py
- tdp/cli/utils.py
- tdp/core/collections.py
- tdp/core/dag.py
- tdp/core/models/deployment_log.py
> Add `--rolling-interval` option to the `tdp plan run` command

- tdp/cli/commands/browse.py
- tdp/cli/commands/plan/dag.py
- tdp/cli/commands/plan/reconfigure.py
- tdp/cli/commands/plan/resume.py
- tdp/cli/commands/plan/run.py
- tdp/cli/utils.py
> Add `--preview` option to the `tdp plan` commands

- tdp/core/variables/cluster_variables.py
Fixes None
Fixes minor type errors
> fix: cluster variables types

- tdp/core/models/deployment_log.py
> feat: filter falsy options from deployment log

- tdp/core/models/deployment_log.py
Fixes None
Store the failed deployment id as an option of the resume deployment log.
> Feat deployment id option for resume

- tdp/core/deployment/deployment_iterator.py
Fixes None
Prevent treating the sleep playbook as a classic operation. Not sure if it is the right way to solve this problem.
> fix: do not update cluster status for sleep operation

- tdp/cli/commands/browse.py
- tdp/cli/queries.py
> fix: browse can display multiples operations

- tdp/core/deployment/deployment_iterator.py
Fixes None
Add the related deployment id to the status log when applicable.
> Link status log to it's deployment id

- tdp/core/deployment/deployment_runner.py
- tdp/core/deployment/executor.py
Fixes None
Log the ansible command that is executed in debug mode.
> Log ansible command in debug mode

- tdp/__init__.py
Fixes None
Set log level to INFO to avoid bloating the output.
> Set log level to info

- tdp/cli/commands/plan/__init__.py
None
Same as #423 for `tdp` command
> print help on `tdp plan` with no subcommands

- tdp/__init__.py
- tdp/cli/__main__.py
- tdp/cli/commands/vars_edit.py
- tdp/cli/logger.py
- tdp/core/cluster_status.py
- tdp/core/collections.py
- tdp/core/dag.py
- tdp/core/deployment/deployment_iterator.py
- tdp/core/deployment/deployment_runner.py
- tdp/core/deployment/executor.py
- tdp/core/models/deployment_log.py
- tdp/core/models/test_models.py
- tdp/core/repository/git_repository.py
- tdp/core/variables/cluster_variables.py
- tdp/core/variables/service_variables.py
Fixes #464
- Allow user to set the log level as an option or an env var
- Remove auto-configuration of the logger in `tdp/__init__.py`
- Define module-level loggers to use Python's hierarchical logging (`logger = logging.getLogger(__name__)`)
> Add option to set log level

- tdp/cli/commands/plan/__init__.py
- tdp/cli/commands/plan/edit.py
- tdp/cli/commands/plan/test_edit.py
- tdp/core/models/deployment_log.py
Fixes #356 
- Tested with following editors : vi, gedit and vscode
> feat: deployment plan edition

- tdp/cli/queries.py
- tdp/core/cluster_status.py
- tdp/core/models/__init__.py
Fixes None
Prevent failure for PostgreSQL which doesn't support MAX on BOOLEAN columns.
> fix: prevent postgres failure on max(bool)

- tdp/cli/commands/plan/__init__.py
Fixes None
The help shortcut is already defined on the root group. It is not necessary to define it again on the `plan` group.
> fix: remove unused group options

- tdp/cli/commands/operations.py
- tdp/cli/commands/plan/ops.py
- tdp/cli/utils.py
Fixes #441 
I didn't test if the hostname doesn't exist : for me it's not necessary.
> feat: Add host option to filter nodes output

- tdp/cli/commands/plan/dag.py
- tdp/core/collections.py
- tdp/core/dag.py
- tdp/core/models/deployment_log.py
> Add options to stop a cluster

- pyproject.toml
- tdp/cli/__main__.py
Fixes None
Create a `main` function. The cli can now be executed as `./tdp/cli/__main__.py`.
Some questions remain:
- Should we add a shebang on top of `__main__.py`?
- Should we rename `__main__.py` to `main.py`? I don't know why we put it that way.
> refactor: create main function

- tdp/core/collections.py
Fixes None
- Make the collections class immutable
- Add a docstring to the module
- Fix types
> Make the `Collections` immutable

- tdp/core/variables/variables.py
Fixes None
Remove the wrapper around the `merge_hash` method as it is not necessary (we don't do it for other imports).
> Use merge_hsash directly from the ansible lib

- tdp/cli/commands/deploy.py
- tdp/core/deployment/deployment_iterator.py
Fixes None
Previous refactor broke operations status.
Ensure to assign the correct status for the whole operation lifecycle and commit it to the database.
> Fix operations status

- tdp/cli/commands/deploy.py
- tdp/cli/queries.py
- tdp/core/deployment/deployment_iterator.py
- tdp/core/deployment/deployment_runner.py
- tdp/core/deployment/test_deployment_runner.py
- tdp/core/models/deployment_model.py
- tdp/core/models/test_deployment_log.py
- tdp/core/models/test_models.py
> Rename status column to state

- tdp/cli/commands/plan/dag.py
- tdp/core/models/deployment_model.py
Fixes None
Add the `--rolling-interval` option to the `tdp plan dag` command.
> feat: add `--rolling-interval` option to `tdp plan dag`

- tdp/core/dag.py
- tdp/core/models/deployment_model.py
Fixes None
Replace `list` type by `Iterable` for node related parameters.
> Replace list types by Iterable for nodes

- tdp/core/models/deployment_model.py
Fixes None
Rename `i` to `operation_order` to be consistent with #506.
> refactor: rename i to operation_order

- tdp/core/deployment/deployment_iterator.py
> fix: add deployment end time when operation fails

- tdp/core/deployment/executor.py
> #514: Resolve ansible command before execution

- tdp/core/variables/service_variables.py
Fixes None
Remove unused method. It was used by the server but should be reworked along with the new version of the server. There is no need to keep it.
> `ServiceVariables`: remove unused method

- tdp/core/variables/schema.py
Fixes None
Refactor broke schema validation.
Not sure why this cast is needed as we already are manipulating a dict.
> Fix schema validation

- tdp/cli/utils.py
Fixes None
Disable variable validation against a schema as it is not stable for now.
> Disable variable validation by default

- scripts/playbooks.py
- tdp/cli/commands/default_diff.py
- tdp/cli/commands/vars/edit.py
- tdp/conftest.py
- tdp/core/collection.py
- tdp/core/collections.py
- tdp/core/constants.py
- tdp/core/dag.py
- tdp/core/deployment/deployment_iterator.py
- tdp/core/models/deployment_model.py
- tdp/core/models/operation_model.py
- tdp/core/models/sch_status_log_model.py
- tdp/core/operation.py
- tdp/core/repository/repository.py
- tdp/core/test_collection.py
- tdp/core/variables/__init__.py
- tdp/core/variables/service_variables.py
Fixes None
Centralize constant definition to:
- Facilitate constant retrieval and edition
- Reduce circular import errors
> Centralize constants definition

- poetry.lock
- pyproject.toml
- test_dag_order/README.md
- test_dag_order/__init__.py
- test_dag_order/conftest.py
- test_dag_order/constants.py
- test_dag_order/helpers.py
- test_dag_order/test_reconfigure.py
Fixes #299
This PR provide code to generate tests that will check if the DAG order is correct based on rules specified in each collections.
Usage instructions have been defined in a `README.md`.
I'm not sure about the packaging of those tests as:
- They must be run from the directory containing the `ansible.cfg` file.
- `pytest` and `tdp-lib` must be available.
> feat: test dag order framework

- poetry.lock
- pyproject.toml
- tdp/core/collections.py
Fixes None
Add Pydantic validation to ensure that dag definition are correct. It also help to prevent error thanks to type inference.
> Add Pydantic validation for DAG files

- tdp/cli/commands/deploy.py
- tdp/core/deployment/deployment_iterator.py
- tdp/core/deployment/test_deployment_runner.py
Fixes #517 
- Changed the `__next__` function of the deployment_iterator to return a callable.
- The current operation running is marked as `RUNNING` in the operation's database.
> refactor: changed __next__ iterator returning a callable

- tdp/core/collection.py
- tdp/core/test_collection.py
Fixes None
Extract the checking logic from the `Collection` class. This make it more testable and prepare the work to remove the `Collection` class.
> refactor: extract check_collection_structure from Collection

- tdp/core/collection.py
Fixes None
I must have failed a rebase previously. This method should have been removed previously.
> Remove legacy method

- tdp/core/collection.py
- tdp/core/collections.py
- tdp/core/test_collection.py
Fixes None
Move the dag files parsing logic to `Collection`. `Collections` can now use directly a dag node that is yield from reading the dag files, we do not need the dag files directly.
> refactor: read dag nodes from files in collection

- tdp/cli/queries.py
Fixes None
- Improve efficiency and readability of the query using windowing instead of grouping.
- Refactor redundant code into functions
- Add parameters to the query (default to the current behavior)
> Improve get_sch_status query

- tdp/cli/commands/status/edit.py
- tdp/cli/commands/status/generate_stales.py
- tdp/cli/commands/status/show.py
- tdp/cli/queries.py
- tdp/dao.py
Fixes None
- Redefine stale query statement parameters: replace `include_stale` and `include_not_stale` bools by `filter_stale` which is an optional bool. If `True` stales are filtered, if `False` stales are filtered out, if `None` no filter is applied.
- Add a `--no-stale` option to the `tdp status show` command.
> Refactor stale param definition

- tdp/cli/commands/status/edit.py
- tdp/cli/commands/status/show.py
- tdp/cli/queries.py
- tdp/core/cluster_status.py
- tdp/core/models/sch_status_log_model.py
- tdp/dao.py
Fixes None
Add the ability to hide a deployed service component from the status list using an `is_active` option. This feature causes a change in the database schema definition.
> feat: add is_active property

- tdp/core/cluster_status.py
- tdp/core/collections.py
- tdp/core/dag.py
- tdp/core/deployment/deployment_iterator.py
- tdp/core/deployment/deployment_runner.py
- tdp/core/entities/operation.py
- tdp/core/models/deployment_model.py
Fixes None
Use a `Operations` class instead of dict to get rid of several utilities methods defined in `Collections`.
> Create Operations class

- tdp/core/conftest.py
- tdp/core/dag.py
Fixes None
- Make `Dag` instances immutables
- Remove unused legacy attributes
- Refactor initialization logic
- Extract the Dag validation logic. IMO, the new `validate_dag_nodes` should not be called inside the `Dag` initialization but in the `Collections._init_operations` method.
> Refactor Dag class

- tdp/core/collection.py
- tdp/core/collections.py
- tdp/core/models/deployment_model.py
- tdp/core/service_component_name.py
- tdp/core/variables/cluster_variables.py
- tdp/core/variables/variables.py
Fixes None
Use `__future__`'s annotations everywhere needed. The previous usage was inconsistent.
> chore: generalize the use of __future__ annotations

- tdp/core/collection.py
- tdp/core/collections.py
- tdp/core/variables/cluster_variables.py
- tdp/core/variables/schema/service_collection_schema.py
- tdp/core/variables/service_variables.py
Fixes None
- Extract reading schema logic from `Collection`.
- Store schemas as a dict of service_name: schema in `Collections`.
> Refactor: store schemas as dict in `Collections`

- tdp/cli/commands/deploy.py
- tdp/cli/commands/plan/reconfigure.py
- tdp/cli/commands/status/edit.py
- tdp/cli/commands/status/generate_stales.py
- tdp/cli/commands/status/show.py
- tdp/cli/commands/vars/edit.py
- tdp/cli/test_get_sch_status.py
- tdp/core/cluster_status.py
- tdp/core/deployment/deployment_iterator.py
- tdp/core/deployment/deployment_runner.py
- tdp/core/deployment/test_deployment_runner.py
- tdp/core/entities/hostable_entity_name.py
- tdp/core/entities/hosted_entity.py
- tdp/core/entities/hosted_entity_status.py
- tdp/core/models/deployment_model.py
- tdp/dao.py
- test_dag_order/conftest.py
Fixes None
Remove `ClusterStatus` parameter from the `Deployment.from_stale_components` method.
> Refactor stale statuses

- tdp/cli/commands/deploy.py
- tdp/core/deployment/deployment_iterator.py
- tdp/core/deployment/executor.py
- tdp/core/deployment/test_deployment_runner.py
Fixes #543 
- The ansible playbook command is now only displayed in mode `DEBUG` and not `INFO`.
- Iterator now also returns the operation record, which is printed with click when deployment is launched.
> Refactor log messages of the logger in the TDP Core

- test_dag_order/conftest.py
Fixes None
In PR #549 ( Refactor log messages of the logger in the TDP Core ) forgot to add operation_rec in the `test_dag_order`.
> fix: add operation_rec for deployment in test_dag_order

- dev/docker-compose.yaml
Fixes None
Added docker compose file with the following databases for development:
- `postgres:15.4`
- `mysql:8.0`
- `mariadb:10.9`
> feat: added database-containers for development

- tdp/cli/commands/browse.py
- tdp/cli/queries.py
- tdp/dao.py
Fixes None
Move the `get_operation_records` query to the DAO class.
> Move `get_operation_records` query to dao

- tdp/cli/commands/browse.py
- tdp/cli/commands/deploy.py
- tdp/cli/commands/plan/dag.py
- tdp/cli/commands/plan/edit.py
- tdp/cli/commands/plan/import_file.py
- tdp/cli/commands/plan/ops.py
- tdp/cli/commands/plan/reconfigure.py
- tdp/cli/commands/plan/resume.py
- tdp/cli/queries.py
- tdp/dao.py
Fixes None
Move the `get_planned_deployment` query to the DAO.
> Move `get_planned_deployment` query to the DAO

- tdp/cli/commands/browse.py
- tdp/cli/queries.py
- tdp/dao.py
Fixes None
Split the `get_deployment` query into several utility queries in the DAO.
This PR is linked to this comment: https://github.com/TOSIT-IO/tdp-lib/pull/592#issuecomment-2152184234
> Move `get_deployments` query to the DAO

- poetry.lock
- pyproject.toml
Fixes None
Fixes numpy version compatibility with matplotlib when installing with pip.
> fix: numpy version

- tdp/core/deployment/deployment_iterator.py
Fixes None
Corrected message where the f-string was forgotten.
> fix: message in iterator for operations affecting stale compoenents

- tdp/cli/__main__.py
Fixes None
Option was injecting the `env` parameter to the main command group which is not used.
> Remove unused parameter injection

- tdp/core/collections/collection_reader.py
- tdp/core/collections/collections.py
- tdp/core/entities/operation.py
- tests/unit/core/test_collection_reader.py
Fixes None
- Introduce the `DagOperation` and `BaseOperation` entities
- Make the `CollectionReader.read_dag_node` yield `DagOperation`
> Introduce `DagOperation` entity

- tdp/core/deployment/deployment_iterator.py
Fixes None
Check if the ongoing operation is a reconfigure operation (hence, its action is restart or config) before trying to update the status of the entity that it affects.
> fix: check reconfigure operation before status update

- dev/docker-compose.yaml
Fixes None
Upgraded Postgres, MariaDB and MySQL databases.
> feat: upgrade dbms in dev

- README.md
- pyproject.toml
> feat(versioning): to version 1.0.0

- tdp/cli/__main__.py
Improve main option callback definition.
> Cleanup main params definition

- scripts/playbooks.py
- tdp/core/collections/collections.py
- tdp/core/dag.py
- tdp/core/entities/operation.py
The `script/playbooks.py` script that generate meta playbooks to opt-out the lib was broken due to previous migrations.
The entities model had to be updated to link a list of source collection to the dag operations.
> Fix script that generates meta playbooks
